# Generated by Django 3.0.3 on 2020-03-03 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200303_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
